[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake",
    "nanobind>=1.4.0",
    "ninja",
    "numpy>=2.0.0b1",
    "packaging",
    "PyYAML",
]
build-backend = "setuptools.build_meta"
